services:
  web:
    build: .
    # nombra la imagen localmente:
    image: devops-tp-skeleton:local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - PORT=3000    por defecto es 3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
