services:
  - type: web
    name: devops-tp-skeleton
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENTRY_DSN
        sync: false
