services:
  - type: web
    name: devops-tp-skeleton
    env: docker
    image: nacho1205/devops-tp:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free
